title                           : RamMap Task Scheduler
description                     : >
  Windows batch script to create scheduled tasks for RAMMap
repository                      : tbr-development/Windows-Deskthemepacks
baseUrl                         : "/RAMMap-Task-Scheduler"
url                             : "//tbr-development.github.io"
show_excerpts                   : false
permalink                       : pretty
remote_theme                    : just-the-docs/just-the-docs
color_scheme                    : "dark"
search_enabled                  : true
enable_copy_code_buttonn        : true
last_edit_timestamp             : true
last_edit_time_format           : "%b %e %Y at %I:%M %p" 
gh_edit_link                    : true
gh_edit_link_text               : "Edit this page on GitHub." 
gh_edit_repository              : "//github.com/tbr-development/Windows-Deskthemepacks" 
gh_edit_branch                  : "main" 
gh_edit_source                  : _docs
gh_edit_view_mode               : "tree"
back_to_top                     : true
back_to_top_text                : "Back to top"  
header_pages                    :
  - index.md
  - instructions.md
  - 404.md
plugins                         :
  - jekyll-seo-tag
  - jekyll-github-metadata
kramdown                        :
  syntax_highlighter_opts       :
    block                       :
      line_numbers              : false

